SonyPradana/php-library

- readme.md
Update readme.md, i will continue update documentaion
> doc: update documentation

- CHANGELOG.md
- src/System/Cron/Schedule.php
- src/System/Cron/ScheduleTime.php
- Added `ScheduleTime->interpolate()` to execute closure. Action after schadule execute.
> feat: add method interpolate to excute log

- .editorconfig
- .gitignore
- CHANGELOG.md
- composer.json
- phpunit.xml
- src/System/Container/Container.php
- src/System/Integrate/Application.php
- src/System/Integrate/Console/Karnel.php
- src/System/Integrate/Http/Karnel.php
- src/System/Integrate/ServiceProvider.php
- src/System/Integrate/helper.php
- tests/Integrate/HelperTest.php
- add app container
- service provider sceleton
- http karnel sceleton
- console karnel sceleton
> feat: application container

- src/System/Integrate/Application.php
- tests/Integrate/HelperTest.php
- add flush method
- add defined cek
- fix default provider config (key name not same)
- add application helper test case.
> feat: add flush application

- src/System/Integrate/Application.php
- prevent application register duplicate service provider
- add DI Aplication self
- prevent application boot before register
> fix: prevent app register duplicate provider

- .github/workflows/php.yml
- composer.json
- src/System/Database/MyPDO.php
- tests/DataBase/QueryStringTest.php
- tests/Integrate/ApplicationTest.php
- tests/Router/BasicRouteTest.php
- tests/Template/BasicTemplateTest.php
- tests/View/RenderViewTest.php
This happen because mypdo throw die function, it make all test not touch.
> [BUG] added mypdo throw exception when conn error

- src/System/Text/Str.php
- tests/Text/StrMacroTest.php
- tests/Text/StrTest.php
string manipulation:
- `Str::chartAt`
- `Str::concat`
- `Str::indexOf`
- `Str::lastIndexOf`
- `Str::match`
- `Str::repalce`
- `Str::search`
- `Str::slice`
- `Str::split`
- `Str::toLowerCase`
- `Str::toUpperCase`
- `Str::firstUpper`
- `Str::firstUppeAll`
- `Str::toPascalCase`
- `Str::toCamelCase`
- `Str::toSnackCase`
- `Str::toCamelCase`
> feat: add string manipulation

- .github/workflows/php.yml
depend on composer.json require php version 7.4 and 8.0. Github action need test some php version too.
> Expand php test version

- src/System/Integrate/Application.php
- src/System/Integrate/Console/Karnel.php
- src/System/Integrate/Exceptions/ApplicationNotAvailable.php
- src/System/Integrate/Http/Karnel.php
- src/System/Integrate/Providers/IntegrateServiceProvider.php
- src/System/Integrate/ServiceProvider.php
- src/System/Integrate/helper.php
- tests/Integrate/ApplicationTest.php
- added Application docblock base on parameter and return type
- add `ApplicationNotAvailable::class` for handle RuntimeException
> doc: added application docblock base on param

- src/System/Text/Exceptions/MacroNotFound.php
- src/System/Text/Exceptions/NoReturn.php
- src/System/Text/Exceptions/PropertyNotExist.php
- src/System/Text/Str.php
- src/System/Text/Text.php
- tests/Text/StrMacroTest.php
- tests/Text/StrTest.php
- tests/Text/TextAPITest.php
- added add `Str::limit` for truncate text with limit length text
- add `MacroNotFound::class`, `NoReturn::class` to handle Exception
- phpstan lv 6 fix paramter and return type in System\Text
> feat: add `Str::limit` for truncate

- src/System/Console/Command.php
- src/System/Console/TraitCommand.php
- tests/Console/ConsoleParseTest.php
Add default console arguments/parameters if argument not found/empty. By pass second argument in constructor.
> Add Default Console Arguments

- src/System/Console/Command.php
- src/System/Console/TraitCommand.php
- added const bold, underline, blink, reverse, hidden
- added const reset bold, underline, blink, reverse, hidden
- rule method provide reset rule parameter
> Added Fourth Parameter Command Rule for Reset Command Line Rule

- src/System/Console/Command.php
- src/System/Console/Decorate.php
- src/System/Console/TraitCommand.php
- tests/Console/ConsoleParseTest.php
- tests/Console/TraitCommandTest.php
- Make `TraitCommand` as Optional (remove from `Command::class` use trait)
- Move const terminal code in `Command::class` to `Decorate::class`
> Make `TraitCommand` as Optional (remove from `Command::class`)

- src/System/Console/Style/Colors.php
- tests/Console/Style/ColorsTest.php
support rgb color (true color) to terminal color
> [Feat] Add RGB Color (true color) Terminal

- src/System/Console/Style/ColorVariant.php
- src/System/Console/Style/VariantColor.php
add more that 200 color variant inspire by tailwind color.
> [Feat] Add Color Variant Hex Color

- src/System/Http/Response.php
- src/System/View/View.php
- tests/Http/ResponseTest.php
- using key val http header
- added __toString as raw respone include header
- fix duplicate header send
> [Refactor] Respone Http Header #50

- src/System/Console/Style/Style.php
- tests/Console/Style/StyleTest.php
adding new style in exist style.
```php
$style = new Style;
$style->push(' info ')->bgBlue();
$body = new Style;
$body->push(' great work');
$style->tap($body)->out();
// info great work
```
> [Feat] Add Suport `Style::tap`

- src/System/Console/Style/Alert.php
- src/System/Console/Traits/AlertTrait.php
- src/System/Console/helper.php
add printer alert in console.
- success: base color green
- info: base color blue
- warn: base color yellow
- fail: base color red
- costume: free color and text
> [Feat] Alert Console Style

- src/System/Http/Request.php
- tests/Http/RequestTest.php
- implement arrayaccess
- $query, $post as Collection
- support get input using __get
- new method query(), post()
> [Feat] `Request::class` implement array access

- src/System/Http/Request.php
- src/System/Http/RequestFactory.php
- pass phpstan lv 6 System\Http
> refactor: formatting

- src/System/Http/RequestFactory.php
> fix: request get content body factory

- src/System/Http/Request.php
- tests/Http/RequestTest.php
- add json request detect
- source return json if supported
- add new method isJson()
> refactor: all with check content type

- src/System/Support/Marco.php
fix call undefind method when call `$this`.
> [Fix] Call Undefind Method

- src/System/Cron/Schedule.php
- src/System/Cron/ScheduleTime.php
Formatting and give parameter and return type.
> [Refactor] Give parameter and Return Type

- src/System/Http/Request.php
- src/System/Integrate/Providers/IntegrateServiceProvider.php
- tests/Http/RequestTest.php
- tests/Integrate/ApplicationTest.php
> [Feat] Support Upload File using Request Macro

- src/System/Database/MyQuery/Insert.php
- tests/DataBase/QueryStringTest.php
- tests/DataBase/RealDatabase/InsertTest.php
```php
MyQuery::from('users', $this->pdo)
->insert()
->raws([
[
'user' => 'sony',
'pwd'  => 'secret',
'stat' => 1,
], [
'user' => 'pradana',
'pwd'  => 'secret',
'stat' => 2,
],
])
->execute();
```
> [Feat] Support Insert Multy Raw

- src/System/Database/MyQuery/Query.php
- tests/DataBase/QueryStringTest.php
> [Feat] Query String With Bind

- src/System/Database/MyQuery/Query.php
- src/System/Database/MyQuery/Select.php
- tests/DataBase/QueryStringTest.php
- tests/DataBase/RealDatabase/SelectTest.php
> [Feat] Support Select Limit Using Offset (#46)

- tests/Support/Facades/FacadeTest.php
new year update
```php
// from
FacadesTestClass::year(2023);
$year = FacadesTestClass::isNextYear();
// to
FacadesTestClass::year(2024);
$year = FacadesTestClass::isNextYear();
```
> [Test] Update Facedes Test

- src/System/Collection/AbstractCollectionImmutable.php
- src/System/Collection/Collection.php
- tests/Collection/CollectionImmutableTest.php
- tests/Collection/CollectionTest.php
Add some collection method
- `rand`
- `shuffle`
- `next`
- `prev`
> [Feat] Add More Collection Method 

- src/System/Database/MyQuery/Select.php
- src/System/Database/MyQuery/Traits/ConditionTrait.php
- tests/DataBase/Query/DeleteTest.php
- tests/DataBase/Query/UpdateTest.php
> [Fix] Support Change Strict Mode in `Delete` and `Update` Query

- src/System/Time/Now.php
- tests/Time/TimeTravelTest.php
* Compare current datetime with same timezone [bug].
* Add methaod to return date with formated [feat].
> [Feat] `Now` Compare with `DateTime` using Same TimeZone

- .github/workflows/php.yml
- src/System/Collection/Collection.php
- src/System/Collection/CollectionImmutable.php
- src/System/Console/Command.php
- src/System/Http/Request.php
- src/System/Router/Route.php
> [Feat] Php 8.1 Support #89

- composer.json
- src/System/Collection/AbstractCollectionImmutable.php
- src/System/Collection/Collection.php
- src/System/Collection/CollectionImmutable.php
- src/System/Collection/Interfaces/CollectionInterface.php
- src/System/Collection/helper.php
- src/System/Text/Str.php
The main gool is yo past phpstan lv 6. And make collection more generic.
> [Refactor] Use Param and Return Type in `Collenction`

- composer.json
- `php-di/php-di` -> 6.4 || 7.0
- `phpunit/phpunit` -> 9.6
- `friendsofphp/php-cs-fixer` -> 3.15
> [Bump] bump-dependency

- src/System/View/Templator.php
- tests/View/TemplatorTest.php
- tests/View/sample/Templators/Slots/layout.php
- tests/View/sample/Templators/comment.php
- tests/View/sample/Templators/else.php
- tests/View/sample/Templators/portofolio.php
- tests/View/sample/Templators/slot.php
Change:
- `{% slot('layout.php',  'title') %}` to `{% extend('layout.php') %} {% slot('title') %}`
- support else in template if
> Fix template engine

- src/System/View/Templator.php
- tests/View/TemplatorTest.php
- tests/View/sample/Templators/comment.php
- tests/View/sample/Templators/nesting.component.php
- tests/View/sample/Templators/nesting.include.php
- support nesting include component
- support template comment `{# your comment #}`
- add property to add suffix in `template_dir`
> [Feat] Enhance Templator

- src/System/Http/Response.php
- tests/Http/ResponseTest.php
usefull for middleware and also for testing
> feat: add `getStatusCode` `getContent`

- src/System/Text/Str.php
- src/System/Text/Text.php
- tests/Text/StrTest.php
- tests/Text/TextAPITest.php
```php
Str::after('https://localhost:8000/test', ':') ;
// //localhost:8000/test
```
> [Feat] find and get text after text

- src/System/Integrate/Application.php
- tests/Integrate/ApplicationTest.php
> [Feat] Add `public_path` helper

- src/System/Console/Style/Style.php
- tests/Console/Style/StyleTest.php
```php
style('hay ')->textBlue()->new_lines()->yeild()->push('im here')->bgRed()->out();
```
> [Feat] Add `yield` print out and continue

- src/System/Http/Request.php
- tests/Http/RequestTest.php
- Add `Request::getRequestFormat()` get request format using header content type.
- Add `Request::getFormat()` get format using mime type.
- Add `Request::getMimeTypes` get mimetype using format.
> [Feat] Request format type

- tests/Console/ConsoleParseAsArrayTest.php
- tests/Console/Style/ColorsTest.php
- tests/Console/Style/StyleTest.php
- tests/Text/StrTest.php
- tests/View/TemplatorTest.php
Suggest add costume exception class every exception instead of create new exception.
> [Test] Remove Deprecated Assertation Test

- src/System/Integrate/Console/MakeCommand.php
- src/System/Integrate/Console/MigrationCommand.php
when create model using make:model not realy use prompt
> [Fix] Hardcode running in production

- readme.md
- src/System/Console/Prompt.php
- src/System/Console/Style/Style.php
- src/System/Console/Traits/AlertTrait.php
- src/System/Console/Traits/PrintHelpTrait.php
- src/System/Console/Traits/PrinterTrait.php
- src/System/Integrate/Console/CronCommand.php
- src/System/Integrate/Console/HelpCommand.php
- src/System/Integrate/Console/Karnel.php
- src/System/Integrate/Console/MigrationCommand.php
- src/System/Integrate/Console/RouteCommand.php
- src/System/Integrate/Console/ServeCommand.php
- replace method name with camelCase
- add new method `replace`
> [Refactor] Deprecate some method and replace it

- src/System/Database/MyModel.php
better chain with retrun  $this for child method return self
> refactor: use return $this instead of self

- composer.json
- src/System/Router/RouteDispatcher.php
friendsofphp/php-cs-fixer from 3.23 to 3.27
> chore, formatting: bump dependency

- src/System/Http/Response.php
- tests/Http/ResponseTest.php
- `isInformational()`
- `isSuccessful()`
- `isRedirection()`
- `isClientError()`
- `isServerError()`
> [Feat] Add response status code type

- tests/Integrate/Console/KarnelTest.php
- change test from default cli to command property
> [Test] Use default in command property

- .github/workflows/php.yml
> [CI] Update workflow dependency

- src/System/Database/Seeder/Seeder.php
- tests/Integrate/Commands/SeedCommandsWithDabaseTest.php
- tests/Integrate/Commands/database/seeders/BasicSeeder.php
- remove App and use MyPdo for handle database seeding (insert)
> [Refactor] Use `MyPdo` instead of `Application`

- src/System/Collection/Collection.php
- tests/Collection/CollectionTest.php
- add `Collection::where`
- add  `Collection::whereIn`
- add  `Collection::whereNotIn`
> [Feat] Add collection where, wherein, wherenotin

- src/System/View/Templator.php
prevent sharing data from external variable
> [Refactor] Encapsulation include file

- src/System/View/Templator.php
- tests/View/TemplatorTest.php
create cache file without excuted
> feat: templator compiler

- src/System/Integrate/Console/CronCommand.php
- src/System/Integrate/Console/HelpCommand.php
- src/System/Integrate/Console/MakeCommand.php
- src/System/Integrate/Console/MigrationCommand.php
- src/System/Integrate/Console/RouteCommand.php
- change command register using pattern matching
- fix match full text when using cmd
> fix, refactor: use pattern command

- src/System/Integrate/Console/MigrationCommand.php
- src/System/Integrate/Console/SeedCommand.php
- optional run seeder after migrate, migrate:fresh, migrate:refresh command
> [Feat] Run seeder after migration command

- src/System/View/Templator.php
- tests/View/TemplatorTest.php
- tests/View/sample/Templators/parent-data.php
- is like global varibale in template, change to prevent same parameter if alerdy same
> refactor: rename parent parameter

- src/System/View/Templator/SectionTemplator.php
- tests/View/Templator/SlotTest.php
- tests/View/Templator/view/section.template
- adding inline section
- inline section will auto escape character
> [Feat] Templator inline slot

- composer.json
- src/System/Database/MyQuery/Select.php
- src/System/Integrate/Console/HelpCommand.php
- src/System/Integrate/Console/RouteCommand.php
- tests/Console/Style/StyleTest.php
- tests/Http/RequestTest.php
- tests/Text/TextTest.php
- update php cs fixer to 3.47
- formatting
> [Chore] Bump dependency

- src/System/View/AbstractTemplatorParse.php
- src/System/View/Templator.php
- src/System/View/Templator/NamespaceTemplator.php
- tests/View/Templator/NamespaceTest.php
- register namespce in templator `{% use ('Some\Namespace') %}`
> feat: templator namespace

- src/System/View/AbstractTemplatorParse.php
- src/System/View/Templator.php
- src/System/View/Templator/UseTemplator.php
- tests/View/Templator/UseTest.php
> refactor, fix: change `namespace` to `use` #282

- src/System/View/Templator/EachTemplator.php
- src/System/View/Templator/NameTemplator.php
- src/System/View/Templator/SetTemplator.php
- tests/View/Templator/CommentTest.php
- tests/View/Templator/ComponentTest.php
- tests/View/Templator/EachBreakTest.php
- tests/View/Templator/EachContinueTest.php
- tests/View/Templator/EachTest.php
- tests/View/Templator/IfTest.php
- tests/View/Templator/NamingTest.php
- tests/View/Templator/ParentDataTest.php
- tests/View/Templator/PhpTest copy.php
- tests/View/Templator/PhpTest.php
- tests/View/Templator/SetTest.php
- tests/View/Templator/view/component.php
- tests/View/sample/Templators/Groups/nesting.php
- tests/View/sample/Templators/each.php
- tests/View/sample/Templators/eachbreak.php
- tests/View/sample/Templators/eachcontinue.php
- tests/View/sample/Templators/naming-ternary.php
- tests/View/sample/Templators/naming.php
- tests/View/sample/Templators/namingskip.php
- tests/View/sample/Templators/parent-data.php
- tests/View/sample/Templators/portofolio.php
- tests/View/sample/Templators/set.php
- tests/View/sample/Templators/slot.php
- tests/View/sample/Templators/slot_miss.php
> [Refactor] Use $ sign to define variable

- .github/workflows/php.yml
- composer.json
is happen, end of life for support version 7.4. Bug fixing and security still support under branch v0.32.
> breaking change: remove support for php7.4

- .php-cs-fixer.php
- rector.php
- src/System/Cron/ScheduleTime.php
- src/System/Database/MyModel/Model.php
- src/System/Database/MyPDO.php
- src/System/Database/MyQuery/Join/AbstractJoin.php
- src/System/Database/MyQuery/Select.php
- src/System/Http/Url.php
- src/System/Integrate/Console/CronCommand.php
- src/System/Integrate/Exceptions/Handler.php
- src/System/Router/Route.php
- src/System/Template/Generate.php
- src/System/Template/Method.php
- ChangeSwitchToMatchRector
- ClassOnObjectRector
- ClosureToArrowFunctionRector
- NullCoalescingOperatorRector
- RestoreDefaultNullToNullableTypePropertyRector
- TernaryToNullCoalescingRector
> refactor: add rector rule

- src/System/Integrate/Console/MigrationCommand.php
> refactor, fix: change visibility `MigrationCommand::$vendor_paths` to public

- readme.md
- src/System/Support/Facades/Facade.php
- tests/Support/Facades/FacadeTest.php
- tests/Support/Facades/Sample/FacadesTestClass.php
> change: allow set Application without initial construct

- src/System/Integrate/Console/Karnel.php
- tests/Integrate/Console/KarnelTest.php
the Jaro similarity score (between 0 and 1)
`Karnel::similar` use 0.8 minimal score
> refactor: change Karnel Console find similarity using `Jaro-Winkler` algo

- src/System/Integrate/Http/Karnel.php
- application contaner register request as string not class-string
> fix: fix kernel alias for request

- .github/workflows/static.yml
- composer.json
------
Added CI for check repo split validataion
> [CI] Added workflow for validate split repo

- src/System/Support/Facades/Hash.php
------
Added facade for Hash Manger
> feat: added `Hash::class` facade

- .github/workflows/split.yaml
- composer.json
- split-repo.php
- src/System/Cache/CacheInterface.php
- src/System/Cache/CacheManager.php
- src/System/Cache/Storage/ArrayStorage.php
- src/System/Cache/composer.json
- src/System/Support/Facades/Cache.php
- tests/Cache/CacheManagerTest.php
- tests/Cache/Storage/ArrayStorageTest.php
> feat: cache

- src/System/Integrate/Console/ClearCacheCommand.php
- tests/Integrate/Commands/ClearCacheCommandTest.php
------
add `ClearCacheCommand::class` for clear the cache (Clear all or spesific driver).
> feat: add `ClearCacheCommand::class` for clear the cache

- bin/split-repo.php
> formatting

- src/System/Integrate/Application.php
- src/System/Integrate/Exceptions/Handler.php
- tests/Integrate/ApplicationTest.php
------
prevent rendering error in production
> fix: convert env (string) to integer

- src/System/Integrate/Testing/TestCase.php
- tests/Integrate/Testing/TestCaseTest.php
------
fix type error, cannot assign null to property Kernel
> fix: fix test assign null (kernel)

- src/System/Integrate/Testing/TestCase.php
------
Add Testcase `call` method, move kernel register to `call` method. prevent application and kernel call not ready.
> fix: `TestCase::class` lifecycle

- src/System/Integrate/Application.php
- src/System/Integrate/Bootstrap/ConfigProviders.php
- tests/Integrate/ApplicationTest.php
- tests/Integrate/assets/app1/config/app.config.php
- tests/Integrate/assets/app2/bootstrap/cache/config.php
- tests/Integrate/assets/app2/config/app.config.php
------
Feat add set date default timezone configure.
> feat: add set date default timezone configure

- src/System/Database/MyQuery.php
- src/System/Database/MyQuery/InnerQuery.php
- src/System/Database/MyQuery/Join/AbstractJoin.php
- src/System/Database/MyQuery/Join/CrossJoin.php
- src/System/Database/MyQuery/Join/FullJoin.php
- src/System/Database/MyQuery/Join/InnerJoin.php
- src/System/Database/MyQuery/Join/LeftJoin.php
- src/System/Database/MyQuery/Join/RightJoin.php
- src/System/Database/MyQuery/Query.php
- src/System/Database/MyQuery/Select.php
- src/System/Database/MyQuery/Table.php
- src/System/Database/MyQuery/Traits/ConditionTrait.php
- src/System/Database/MyQuery/Where.php
- tests/DataBase/Query/DeleteTest.php
- tests/DataBase/Query/JoinTest.php
- tests/DataBase/Query/SelectTest.php
- tests/DataBase/Query/UpdateTest.php
- tests/DataBase/RealDatabase/SubQueryTest.php
Introduce InnerQuery type for table names, enhance join classes to support sub-queries, and improve type hinting in MyQuery classes. Add tests for SubQuery scenarios to ensure functionality.
> feat: add support sub query builder 

- src/System/Time/Now.php
- tests/Time/TimeTravelTest.php
------
revent last pr use manual calculate age.
> revent: use manual age calculation

- src/System/Database/MyQuery/Replace.php
- src/System/Database/MyQuery/Table.php
- tests/DataBase/Query/ReplaceTest.php
- tests/DataBase/RealDatabase/ReplaceTest.php
| Fixed issues | #412 |
------
Introduce a new Replace query class and corresponding methods in the Table class. Add comprehensive tests to ensure correct functionality for inserting and replacing data in the database.
> feat: implement Replace query functionality and corresponding tests

- src/System/Http/Request.php
- tests/Http/RequestTest.php
…ders
------
Add methods to retrieve Authorization and Bearer token from header request.
> feat: add methods to retrieve Authorization and Bearer token from header

- src/System/View/Templator.php
- src/System/View/Templator/BooleanTemplator.php
- src/System/View/Templator/DirectiveTemplator.php
- tests/View/Templator/BooleanTest.php
| Is bugfix?   | **No**|
| New feature? | **Yes**|
| Breaks BC?   | **No**|
------
New templator directive, bool. to echo string of boolean ('true' or 'false').
> feat: templator boolean

- tests/View/Templator/ComponentTest.php
| Is bugfix?   | **No**|
| New feature? | **No**|
| Breaks BC?   | **No**|
------
fix windows test issue for new line.
> test: fix windows test

- src/System/View/AbstractTemplatorParse.php
- src/System/View/DependencyTemplatorInterface.php
- src/System/View/Templator.php
- src/System/View/Templator/ComponentTemplator.php
- src/System/View/Templator/IncludeTemplator.php
- src/System/View/Templator/SectionTemplator.php
- tests/View/Templator/ComponentTest.php
- tests/View/Templator/IncludeTest.php
- tests/View/Templator/SectionTest.php
| Is bugfix?   | **Yes / No**                                              |
| New feature? | **Yes / No**                                              |
| Breaks BC?   | **Yes / No**                                              |
------
Introduce a dependency management system in the templator, allowing for better organization and retrieval of dependencies. Update the method signature for template processing to accommodate the new functionality.
> Implement templator with dependency management

- src/System/Integrate/Console/ViewCommand.php
------
Introduce a new command to monitor changes in view files, allowing for real-time updates and cache clearing when modifications occur.
> Add 'view:watch' command to monitor view file changes

- src/System/View/Templator/SectionTemplator.php
- tests/View/Templator/SectionTest.php
- tests/View/Templator/view/sectiondefault.template
- tests/View/Templator/view/sectiondefaultandmultylines.template
- tests/View/Templator/view/sectiondefaultmultylines.template
------
Introduce improved section handling capabilities in the SectionTemplator, including support for default yield parameters. Add tests to verify the new functionality.
> feat: enhance SectionTemplator with new section handling and default yield support

- src/System/View/Templator/IfTemplator.php
- tests/View/Templator/IfTest.php
| Is bugfix?   | **Yes**|
| New feature? | **No** |
| Breaks BC?   | **No**|
------
Enhance the Templator to correctly handle nested if statements and improve the parsing logic for conditional templates. Add tests to verify the rendering of nested if and if-else structures.
> Fix Templator for nested if statements

- src/System/Router/Router.php
- tests/Router/GroupRouteTest.php
------
Improve the prefix grouping functionality to support nested routes and add tests to verify the behavior of nested prefixes.
> Enhance prefix grouping functionality with nested routes test

- tests/Collection/CollectionTest.php
> test: refactor test methods for clarity and consistency

- src/System/Integrate/Console/MigrationCommand.php
- tests/Integrate/Commands/MakeCommandsWithDatabaseTest.php
- tests/Integrate/Commands/SeedCommandsWithDabaseTest.php
- tests/Integrate/Commands/database/seeders/UserSeeder.php
------
implement migration table deletion after successful rollback.
> feat: implement migration table deletion after successful rollback

- resources/facades.php
- src/System/Support/Facades/View.php
- src/System/Support/Facades/Vite.php
------
Add new facade class View aka Templator and Vite. Add dx facade. the accessor from application alias container.
> feat: register View and Templator to Facade class
