SonyPradana/php-library

src/System/Console/Command.php
src/System/Console/TraitCommand.php
tests/Console/TraitCommanndTest.php

- Fixed wrong color code.
- Added text and background color cyan, magenta, light cyan, light magenta, light red, light yellow, light blue, light gray, dark gray.
- Added just in time text and background color (0-256) color code.
- Added Bold, underline, reverse and hidden.
- Test unit for `TraitConsole`.

More Commandline Color Palette

---

src/System/Console/Style/Decorate.php
src/System/Console/Traits/CommandTrait.php
src/System/Console/Traits/PrinterTrait.php
tests/Console/ConsoleParseTest.php
tests/Console/TraitCommandTest.php

Restructur folder (organize fooder)
- move traitcommand.php to traits folder
- move decorate.php to styles folder
- splint trait code (new printertrait.php)
the reason refactor structur folder is to make more easy to maintans code. In feature trait or style may be more that one trait or style.

Restructor folder/file tree

---

src/System/Console/Style/Colors.php
tests/Console/Style/ColorsTest.php
tests/Console/Style/StyleTest.php

Support hex color by translate hex to rgb color (true color).
```php
[$r, $g, $b] = sscanf($hex_code, '#%02x%02x%02x');
```
also rename method for consistan method name.
`Colors::hexRawText()` -> `Colors::hexText()`
`Colors::hexRawBg()` -> `Colors::hexBg()`

[Refactor] Support Console Hex Color (true color)

---

src/System/Console/Style/Style.php
tests/Console/Style/StyleTest.php

support add text/bg color with color variant (eg; blue_500, blue_100) using magic call.
```
style('text')->text_blue_300()->bg_green_100();
```
using prefix `text_` or `bg_` follow by supported color variant.
see [ColorVariant.php](https://github.com/SonyPradana/php-library/blob/master/src/System/Console/Style/ColorVariant.php)

[Feat] Add Support Color Variant in Style

---

src/System/Console/Command.php
src/System/Console/Traits/PrintHelpTrait.php

- added trait to print option and argument using array
- deprecated `Command::printHelp`
```php
// Some class extend with Command
use PrintHelpTrait;
public function main()
{
$this->option_describes = [
'test' => 'this will display on your console',
'test:console' => 'this will display on your console',
];
$this->argument_describes = [
'--name' => 'set name',
'--age'  => 'set age'
];
$this->option_relation = [
'test' => ['--name', '--age'],
'test:console' => ['--age']
];
$this->printOption(new Style)->out();
$this->printArgument(new Style)->out();
}
```

[Feat] Print Help for Option and Argument #51

---

src/System/Console/Style/Style.php

- Fix missing style (param) when merge to style tap.
- New method `Style::toString` render rule with customize text and ref.

[Fix] Missing Ref When Using `Style::tap`

---

src/System/Integrate/Http/Karnel.php
src/System/Router/AbstractMiddleware.php
src/System/Router/Router.php

in case some handle middleware request some parameter its nor support in `AbstractMiddleware::class`.
```php
class SomeMiddleware
{
public function handle(Request $request)
{
}
}
```

[deprecated] `AbstarctMiddleware::handel`

---

src/System/Database/MyQuery/Select.php
src/System/Database/MyQuery/Traits/ConditionTrait.php
tests/DataBase/Query/DeleteTest.php
tests/DataBase/Query/JoinTest.php
tests/DataBase/Query/UpdateTest.php

before
```sql
SELECT * FROM `base_table` INNER JOIN join_table_1 ON base_table.base_id = join_table_1.join_idWHERE ( (base_table.a = :a) )
``` 
to
```sql
SELECT * FROM `base_table` INNER JOIN join_table_1 ON base_table.base_id = join_table_1.join_id WHERE ( (base_table.a = :a) )
```

[Fix] Query Concat `Join` and `Where` Statment

---

src/System/Database/MyQuery/Query.php
tests/DataBase/Query/SelectTest.php

Query Bind Boolean Type Return as Boolean (string `instead` of int).
```php
MyQuery::from('test', $this->PDO)
->select(['column_1', 'column_2', 'column_3'])
->equal('column_1', 123)
->equal('column_2', 'abc')
->equal('column_3', true)
;
```
```sql
SELECT `column_1`, `column_2`, `column_3` FROM `test` WHERE ( (test.column_1 = 123) AND (test.column_2 = 'abc') AND (test.column_3 = 1) )
```
```sql
SELECT `column_1`, `column_2`, `column_3` FROM `test` WHERE ( (test.column_1 = 123) AND (test.column_2 = 'abc') AND (test.column_3 = true) )
```

[Fix] Query Bind Boolean Type Return as Boolean

---

src/System/Console/Command.php
tests/Console/ConsoleParseTest.php

Bc alert
Commnad argv parse with '-' instead of ''.
```bash
php cli --some-param test
```
Before to get `test` as result
`someparam`
After 
`some-param`

[Refactor] Command Parse with Minus '-' 

---

src/System/Console/Command.php
tests/Console/ConsoleParseAsArrayTest.php

`Command::class` implement array access. 
access from array
```php
// argv: php cli --some-text hello
// without array access
$cmd->__get('some-text'); 
// with array access
$cmd['some-text'];
```
both can be use to get 'hello' from `argv` command input

[Feat] Command Implement `ArrayAccsess`

---

src/System/Http/Request.php
tests/Http/RequestTest.php

add request duplicate to modifie request. Usefull for handdle request in middle where sometime need to be modifie.
```php
public function handle(Request $req, Closure $next): Response 
{
return $next($req->duplicate(query: ['auth'=>123]);
}
```

[Feat] Add `Request::duplicate()`

---

src/System/Http/Request.php

- php 7.4 doest support native return static type

[Fix] Return native static type in php 7.4

---

src/System/Http/Response.php

inspire by [Flush with flush() after ob_end_flush()](https://github.com/symfony/symfony/commit/118acea77a24c20dc8fd13f6ddefba0f85c77ca8) in Symfony response.

[Refactor] Flush with `flush()` after `closeOutputBuffers`

---

src/System/Router/RouteGroup.php

`RouteGroup::grup` will return same as callback return (generic <T>)

[Fix] `RouteGroup::grup` return as callback

---

src/System/Console/helper.php

[Feat] Exit prompt confirmation

---

src/System/View/Templator/SectionTemplator.php
tests/View/Templator/SlotTest.php

uses,
```php
{% extend(\'section.template\') %}
{% sections %}
title: taylor
language: php
{% endsections %}
```

feat: templator multy section

---

src/System/Integrate/Application.php
src/System/Integrate/Bootstrap/BootProviders.php
src/System/Integrate/Bootstrap/RegisterProviders.php
src/System/Integrate/Console/Karnel.php
src/System/Integrate/Http/Karnel.php
tests/Integrate/ApplicationTest.php
tests/Integrate/Bootstrap/BootProvidersTest.php
tests/Integrate/Bootstrap/RegisterProvidersTest.php
tests/Integrate/Console/KarnelTest.php
tests/Integrate/Http/KarnelTest.php

- add karnel register appliaction bootstrapper
- add BootProvider: to call `Application::bootProvider`
- add RegisterProvider: to call `Application::registerProvider`

feat, refactor: application with bootstrapper

---

src/System/Integrate/Console/HelpCommand.php
src/System/Integrate/Console/Karnel.php
src/System/Integrate/Console/Util.php
tests/Integrate/Commands/HelpCommandsTest.php
tests/Integrate/Console/KarnelTest.php

- load command config now wrap in array (no need array merge), so this util use for flatten wrapper array

refactor: load config using `Util::loadCommandFromConfig()`

---

src/System/Collection/AbstractCollectionImmutable.php

why we chosed to raname without depracted. this method call for dump data (uder dev) its not effect in production.

fix: change typo method name

---

src/System/Support/Facades/Facade.php
tests/Support/Facades/FacadeTest.php

- `Facade::class` use `Application::make()` instead of `Application::get()` to make more consistent

feat: improve facade create instance

---

src/System/Http/RequestFactory.php

- add new method  `RequestFactory::capture()`
- deprecated `getFromGloball` and added `getFromGlobal`

feat: register `HTTP_AUTHORIZATION` to header if available

---

src/System/Support/Facades/Cache.php

------
Change facade accesor for `Cache` to `cache` instead of `CacheManager::class`.

refactor: change cache facade accessor

---

src/System/Http/Request.php

not BC but improvement `source()` union of `all()`
------
Not BC but improvement `source()` union of `all()`.

refactor: change global __get return form `source()` to `all()`

---

src/System/View/Exceptions/DirectiveCanNotBeRegister.php
src/System/View/Exceptions/DirectiveNotRegister.php
src/System/View/Templator.php
src/System/View/Templator/DirectiveTemplator.php
tests/View/Templator/DirectiveTest.php

------
Add costume directive use by templator

feat: add costume directive use by templator

---

src/System/Cache/Storage/FileStorage.php
tests/Cache/Storage/FileStorageTest.php
tests/Cache/Storage/cache/.gitignore

------
_Add new driver cache storage using file system._

feat: add `FileStorage` for cache driver

---

src/System/Cache/Storage/FileStorage.php

------
Prevent cache `FileStorage::class` delete gitignore when call `clear` method.

fix: prevent cache `FileStorage::class` delete gitignore

---

src/System/Integrate/Application.php
tests/Integrate/ApplicationTest.php

------
php-library have two feature witch require some configuration. password manager need bcrypt round (2 is default). cache manager file storage.
- add `bcrypt_rounds` and `cache_store`

feat: add missing aplication configuation

---

src/System/Cache/CacheManager.php
tests/Cache/CacheManagerTest.php

------
Allowing lazy load driver without initial driver, by adding closure driver it will load if needed (without initial first).

fix: allow set driver using closure

---

src/System/Integrate/Console/MigrationCommand.php

| Deprecated?   | **Yes**                                              |
------
remove `take` option from running migration

fix: migration always use latest batch intead using take

---

.github/workflows/database.yml
src/System/Integrate/Console/MigrationCommand.php
tests/Integrate/Commands/MigrationCommandsTest.php

------
Change base connection testcase.

test: change base connection testcase

---

.github/workflows/database.yml
composer.json
src/System/Database/MySchema/Table/Alter.php
tests/DataBase/MySchemaTest.php
tests/DataBase/Query/Schema/Table/AlterTest.php
tests/DataBase/RealDatabase/Schema/Table/AlterTest.php

------
Fix database query builder alter dilimater.

fix: fix database query builder alter dilimater

---

src/System/Time/Now.php
tests/Time/TimeTravelTest.php

| Breaks BC?   | **Yes**                                              |
------
Correct the age calculation logic to accurately reflect the difference in years and enhance code formatting for better readability. bc return integer instead of float.

fix: correct age calculation and improve code formatting

---

src/System/Database/MyQuery/Query.php
src/System/Database/MyQuery/Select.php
tests/DataBase/Query/SelectTest.php
tests/DataBase/RealDatabase/SubQueryTest.php

------
Introduce a groupBy method to facilitate grouping in SQL queries. Update tests to verify the correct functionality of the new method.

feat: implement groupBy method for SQL queries and update tests

---

src/System/Database/MyModel/Model.php
src/System/Database/MyQuery/Query.php
src/System/Database/MyQuery/Select.php
tests/DataBase/Query/SelectTest.php

| Fixed issues | #106 |
------
Improve sorting capabilities by allowing multiple order specifications and adding methods to handle null checks in queries.

feat: enhance sorting functionality with multi-order support and null checks

---

src/System/Database/MyQuery/Delete.php
src/System/Database/MyQuery/Query.php
src/System/Database/MyQuery/Traits/ConditionTrait.php
src/System/Database/MyQuery/Update.php
tests/DataBase/Query/JoinTest.php
tests/DataBase/RealDatabase/JoinTest.php

------
Introduce functionality to handle joins in delete and update queries, including support for table aliases. This enhancement allows for more complex query structures while maintaining proper binding of values.

feat: add join support for delete and update queries with alias handling

---

src/System/Database/MyModel/Model.php

| Is bugfix?   | **Yes (ci/cd)**                                              |
------
Refactor model instantiation to use a static reference instead of a hardcoded class name and improve return type annotations for better type safety.

refactor: static reference for model instantiation and update return type annotations

---

src/System/Http/JsonResponse.php
src/System/Http/Response.php
tests/Http/JsonResponseTest.php

| Is bugfix?   | **No**|
| New feature? | **Yes** |
------
new json response class instead using `Response::json()`. json() will deprated and soon be removed, also content will alwasy as string. content type will follow the header.

feat: Json Response

---

src/System/View/Templator/EachTemplator.php
tests/View/Templator/EachTest.php

| Is bugfix?   | **Yes**|
| New feature? | **No**|
| Breaks BC?   | **No**|
------
Correct the foreach syntax in the EachTemplator class and update tests to reflect the changes. Add new tests for nested foreach and multiple foreach blocks.

Fix foreach syntax in EachTemplator

---

.github/workflows/php.yml

Update the GitHub Actions workflow to include PHP 8.4 in the testing matrix.

Add PHP 8.4 to testing matrix in GitHub Actions

---

src/System/View/Templator/NameTemplator.php
tests/View/Templator/NamingTest.php

Enhance the NameTemplator to handle unescaped variables and add a corresponding test to verify this functionality.

Update NameTemplator to support unescaped variables

---

src/System/Integrate/Http/Karnel.php
tests/Integrate/Http/KarnelTest.php

------
This pull request adding routers parameter to the requests attribute. we are adding in the began of middleware, it's make parameters can be access from Middleware event not yet touch the controller.

[feat] Adding request parameters handling in Karnel

---

src/System/Collection/Collection.php
tests/Collection/CollectionTest.php

| Breaks BC?   | **Yes**                                              |
------
deprecated typo method `reduse` and add `reduce`. nothing else.

[refacto] Correct typo in reduce method name and add deprecated alias

---

src/System/Router/Route.php
tests/Router/NamedParameterRouteTest.php

| Breaks BC?   | **YNo**                                              |
------
fix route name missing when initial (construction), it becouse the route name has been set ovverides with prefix withtoun actual route name. fix thi issue for #447.

fix: missing route name

---

src/System/Console/Command.php

------
For the shell’s purposes, a command which exits with a zero exit status has succeeded. So while an exit status of zero indicates success, a non-zero exit status indicates failure. This seemingly counter-intuitive scheme is used so there is one well-defined way to indicate success and a variety of ways to indicate various failure modes.
When a command terminates on a fatal signal whose number is N, Bash …

feat: command exit const

---

src/System/Database/MyPDO.php
tests/DataBase/PDO/TransactionTest.php

| Breaks BC?   | **No**                             |
| Fixed issues | #444 |
------
Auto rollback when pdo transection got failed

refacto: transaction throw exception will cancel transection directly

---

resources/facades.php
src/System/Integrate/Console/MigrationCommand.php
src/System/Support/Facades/PDO.php
tests/DataBase/TestDatabase.php
tests/Integrate/Commands/MigrationCommandsTest.php

| Breaks BC?   | **Yes**                                              |
------
Refactor PDO Facade to use `DatabaseManager` as accessor intead pf `MyPDO`. Because no longger use `MyPDO` as accossor some method not include may broken the api. The Database manager has same Interface with `MyPDO`, we use `ConnectionInterface`. This list of mmethod not cover by interface (BC).
1. conn()
2. configs()
3. getDsn()

refactor: use database manager as PDO accessor
